/** Examples are contracts, not invented evidence. Replace every placeholder by actual reads. */
export const STUDY_SCHEMA = {
	version: 1,
	rules: [
		"Read state first; use current identifiers and revision zero only for new documents.",
		"A sourceHash is the raw SHA-256 from read_source. Line anchors refer to extracted text, not PDF pages.",
		"A matching quote proves provenance only, not the truth of the claim. Mark incomplete coverage and uncertainty.",
		"All fields in these examples are required. Arrays may be empty unless noted. Unknown fields are rejected.",
		"Run approval and progress belong to the human UI. There is no agent run/approve command.",
	],
	anchor: {
		sourceId: "FROM_STATE",
		sourceHash: "64-lowercase-hex-FROM_READ",
		startLine: 1,
		endLine: 3,
		quote: "exact text inside these lines",
	},
	save_roadmap: {
		scope: "article identity / chapter and omitted sections",
		story: "problem → idea → evidence → limits",
		contribution: "author claims versus assessed support",
		uncertainties: ["unchecked steps / missing prerequisites"],
		nodes: [
			{
				id: "node-1",
				kind: "background|notation|definition|contribution|proof|implementation|example",
				title: "unit title",
				epistemicStatus: "unchecked",
				dependsOn: [],
				explanation: "Markdown with $math$; derive steps, assumptions, examples and failure cases",
				whyNeeded: "minimal prerequisite / role in the main claim",
				checks: ["concrete question or check (at least one)"],
				sources: [],
				openQuestions: ["uncertainties"],
			},
		],
	},
	roadmapLimits:
		"epistemicStatus unchecked|argument-given|gap|candidate-error (not a proof certificate). 1..120 nodes, acyclic prerequisite graph; contribution/proof/implementation nodes need actual anchors; scope long textbooks by chapter.",
	save_note: {
		nodeId: null,
		anchor: null,
		body: "Markdown, $math$, explanation or concern. Author is injected by Host; never submit author.",
	},
	save_proposal: {
		title: "one direction",
		nodeIds: ["actual roadmap node id"],
		hypothesis: "falsifiable idea",
		whyUseful: "impact, feasibility and why better than alternatives",
		alternatives: ["strong simpler alternative"],
		risks: ["assumption / limitation"],
		requiredEvidence: ["what would support or refute it"],
		noveltyStatus: "not-established",
		sources: [],
	},
	save_experiment: {
		title: "minimal experiment",
		purpose: "study",
		proposalId: null,
		hypothesis: "what is checked",
		baseline: "strong baseline or known result",
		ablations: [],
		metric: "what is measured",
		dataSplit: "toy / train-validation-test; prevent leakage",
		seeds: [1],
		successCriterion: "predefined criterion",
		failureInterpretation: "what a negative result means",
		language: "python",
		code: "print(2+2)",
		timeoutSeconds: 5,
	},
	experimentLimits:
		"purpose study|research; research requires an actual current proposalId. language python|javascript. Timeout 1..30 seconds. Source/roadmap/proposal/code edits invalidate previous approval. No automatic package installation, files from the source folder, shell, or autonomous running. Reruns require a new revision and human approval. Runtime is trusted local code, not an OS sandbox.",
};
