import assert from "node:assert/strict";
import {mkdtempSync,rmSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import test from "node:test";
import {createJiti} from "jiti";
const dir=mkdtempSync(join(tmpdir(),"pi-course-builder-web-"));
const previousHarnessDirectory=process.env.PI_LEARNING_HARNESS_DIR;
process.env.PI_LEARNING_HARNESS_DIR=dir;
const jiti=createJiti(import.meta.url,{tsconfigPaths:true});
const {inspectModePackInventory,buildModePackRuntimePlanFromInventory,collectModePackRuntimeEvidence}=await jiti.import("./mode-pack-inventory.ts");
const {verifyModePackRuntime}=await jiti.import("../../../packages/mode-pack-host/src/index.ts");
const {resolveModePackSnapshot}=await jiti.import("../../../packages/profile-resource-host/src/index.ts");
const {parseCourseBuilderFiles}=await jiti.import("./course-builder-import.ts");
const extension=(await jiti.import("./course-builder-extension.ts")).default;
const {getLearningHarness}=await jiti.import("./harness-server.ts");

test.after(()=>{
 getLearningHarness().close();
 globalThis.__piLearningHarness=undefined;
 if(previousHarnessDirectory===undefined)delete process.env.PI_LEARNING_HARNESS_DIR;
 else process.env.PI_LEARNING_HARNESS_DIR=previousHarnessDirectory;
 rmSync(dir,{recursive:true,force:true});
});
test("Course Builder mode resolves physical plugin, authoring tools and fixed guidance",async()=>{
 const inventory=await inspectModePackInventory(dir);const definition=inventory.builtinPacks["course-builder"];
 assert.ok(definition);assert.deepEqual(definition.tools,["bash","codemode","edit","read","write"]);
 const snapshot=resolveModePackSnapshot({pack:definition,courseVersionId:null,catalog:inventory.catalog});
 const plan=buildModePackRuntimePlanFromInventory({snapshot,inventory,definition});
 assert.equal(plan.extensionPaths.length,1);assert.match(plan.extensionPaths[0],/course-builder-extension\.ts$/);
 assert.match(plan.systemPrompt,/teacher review/i);assert.doesNotMatch(plan.systemPrompt,/Noi1r/);
 assert.match(plan.systemPrompt,/course-production/u);assert.match(plan.systemPrompt,/workflow_prepare/u);assert.match(plan.systemPrompt,/workflow_start/u);
 assert.match(plan.systemPrompt,/Only that branch loads its full teaching methods/u);
 assert.doesNotMatch(plan.systemPrompt,/Assume earlier scheduled lessons have been taught/u);
 assert.ok(definition.components.some(c=>c.type==="plugin"&&c.id==="course-builder"&&c.required&&c.enabled));
 const caw=definition.components.find(c=>c.type==="skill"&&c.id==="pi-caw");
 assert.ok(caw?.enabled,"Course Builder must expose the native pi-CAW Skill");
 assert.equal(caw.delivery,"native-skill");
 const resource=inventory.resourcesByKey.get("skill:pi-caw");
 assert.ok(resource);
 assert.equal(resource.synthetic,false,"pi-CAW must be a physical Skill");
 assert.equal(resource.paths.length,1,"pi-CAW must have one SKILL.md path");
 assert.ok(plan.skillPaths.includes(resource.paths[0]),"pi-CAW must use Pi native Skill discovery");
 assert.ok(plan.expected.loadedSkillIds.includes("pi-caw"),"the native Skill must be verified as loaded");
 assert.equal(plan.systemPrompt.includes(resource.text),false,"the full pi-CAW Skill body must stay out of the eager system prompt");
 assert.doesNotMatch(plan.systemPrompt,/mode-pack-resource id="skill:/u);
});
test("resource verification rejects a missing native Skill even when the mode prompt survives",async()=>{
 const inventory=await inspectModePackInventory(dir),definition=inventory.builtinPacks.general;
 const snapshot=resolveModePackSnapshot({pack:definition,courseVersionId:null,catalog:inventory.catalog});
 const plan=buildModePackRuntimePlanFromInventory({snapshot,inventory,definition});
 const loadedSkills=plan.skillPaths.map(filePath=>({filePath}));
 const session={getActiveToolNames:()=>snapshot.tools,agent:{state:{systemPrompt:plan.systemPrompt}},resourceLoader:{getSkills:()=>({skills:loadedSkills}),getExtensions:()=>({extensions:[]}),getPrompts:()=>({prompts:[]}),getThemes:()=>({themes:[]})}};
 assert.equal(verifyModePackRuntime(snapshot,collectModePackRuntimeEvidence(session,plan),plan.expected).verified,true);
 session.resourceLoader.getSkills=()=>({skills:[]});
 const result=verifyModePackRuntime(snapshot,collectModePackRuntimeEvidence(session,plan),plan.expected);
 assert.equal(result.verified,false,"the prompt cannot prove that a selected native Skill was loaded");
});
test("Actual extension registers only a dedicated agent surface, with no teacher approval action",async()=>{
 const tools=[],events=[];extension({registerTool:tool=>tools.push(tool),on:(name,handler)=>events.push({name,handler}),events:{on:()=>()=>{},emit:()=>{}},appendEntry:()=>{},sendMessage:()=>{}});
 assert.deepEqual(tools.map(t=>t.name),["course_builder"]);
 assert.deepEqual(events.map(event=>event.name),["session_start","session_shutdown","before_agent_start","message_start","input","agent_end","agent_settled"]);
 const ctx={sessionManager:{getSessionId:()=>"test-unbound-session",getBranch:()=>[]}};
 const result=await tools[0].execute("call",{action:"state"},new AbortController().signal,undefined,ctx);
 assert.equal(JSON.parse(result.content[0].text),null);
 await assert.rejects(tools[0].execute("call",{action:"accept"},undefined,undefined,ctx),/not available/);
});
test("Web importer reads text and retains unknown formats without extension filtering",async()=>{
 const files=await parseCourseBuilderFiles([new File(["# Course"],"course.md"),new File([Uint8Array.of(0,1,2,3)],"notes.docx")]);
 assert.equal(files[0].extractedText,"# Course");assert.equal(files[0].kind,"markdown");
 assert.equal(files[1].kind,"asset");
 assert.match(files[1].extractedText,/no text adapter/i);
});
