import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, existsSync, rmSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import test from "node:test";
import { createJiti } from "jiti";
const jiti = createJiti(import.meta.url, { tsconfigPaths: true });
const { installLocalSkills, readLocalSkillLock } = await jiti.import("./local-skill-install.ts");
const { annotateSkillsWithInstallInfo } = await jiti.import("./skill-lock.ts");
const { loadSkillsFromDir } = await jiti.import("@earendil-works/pi-coding-agent");

test("project installer preserves complete folders, metadata, and existing skills; updates stay in the same library", async (t) => {
  const root = mkdtempSync(join(tmpdir(), "pi-skill-install-"));
  const directory = join(root, "skills");
  mkdirSync(directory);
  t.after(() => rmSync(root, { recursive: true, force: true }));
  const content = "---\nname: full-fixture\ndescription: Complete fixture with supporting resources.\n---\nRead references/guide.md and run scripts/test.js when asked.\n";
  let version = "version-one";
  const run = async (args, options) => {
    assert.ok(args.includes("--copy"));
    assert.ok(!args.includes("-g"));
    assert.notEqual(options.cwd, directory);
    const skillDir = join(options.cwd, ".pi", "skills", "full-fixture");
    mkdirSync(join(skillDir, "references"), { recursive: true });
    mkdirSync(join(skillDir, "scripts"));
    writeFileSync(join(skillDir, "SKILL.md"), content);
    writeFileSync(join(skillDir, "references", "guide.md"), `Full reference ${version}`);
    writeFileSync(join(skillDir, "scripts", "test.js"), "// preserved script\n");
    writeFileSync(join(options.cwd, "skills-lock.json"), JSON.stringify({ version: 1, skills: { "full-fixture": { source: "fixture/repo", sourceType: "github", skillPath: "skills/full-fixture/SKILL.md", computedHash: version } } }));
    return { stdout: "Installation complete", stderr: "" };
  };
  await installLocalSkills("fixture/repo@full-fixture", { directory, run });
  assert.equal(readFileSync(join(directory, "full-fixture", "SKILL.md"), "utf8"), content);
  assert.equal(readFileSync(join(directory, "full-fixture", "references", "guide.md"), "utf8"), "Full reference version-one");
  assert.ok(existsSync(join(directory, "full-fixture", "scripts", "test.js")));
  const skills = annotateSkillsWithInstallInfo(loadSkillsFromDir({ dir: directory, source: "test" }).skills, { cwd: root, agentDir: join(root, "agent"), localSkillsDirectory: directory });
  assert.equal(skills[0].install.directory, directory);
  assert.equal(skills[0].install.package, "fixture/repo@full-fixture");
  assert.equal(skills[0].install.canCheckForUpdates, true);
  await assert.rejects(installLocalSkills("fixture/repo@full-fixture", { directory, run }), /already exists/);
  version = "version-two";
  await installLocalSkills("fixture/repo@full-fixture", { directory, run, update: true });
  assert.equal(readLocalSkillLock(directory).skills["full-fixture"].computedHash, "version-two");
  assert.equal(readFileSync(join(directory, "full-fixture", "references", "guide.md"), "utf8"), "Full reference version-two");
  await assert.rejects(installLocalSkills("broken/repo", { directory, run: async () => ({ stdout: "Installation complete", stderr: "" }) }), /did not produce Pi skill files/);
  assert.deepEqual(readdirSync(root), ["skills"], "staging is cleaned without leaving another installed library");
});

test("real skills CLI installs a local source into the configured project directory", { skip: process.env.PI_TEST_REAL_SKILLS_CLI !== "1", timeout: 180_000 }, async (t) => {
  const root = mkdtempSync(join(tmpdir(), "pi-skill-cli-"));
  t.after(() => rmSync(root, { recursive: true, force: true }));
  const directory = join(root, "skills");
  const source = join(root, "source");
  mkdirSync(directory); mkdirSync(source);
  writeFileSync(join(source, "SKILL.md"), "---\nname: native-install-fixture\ndescription: Native CLI test.\n---\nComplete locally installed skill.\n");
  writeFileSync(join(source, "reference.txt"), "supporting content");
  const previousDirectory = process.env.PI_SKILLS_DIR;
  const previousAgent = process.env.PI_CODING_AGENT_DIR;
  process.env.PI_SKILLS_DIR = directory;
  process.env.PI_CODING_AGENT_DIR = join(root, "agent");
  t.after(() => {
    if (previousDirectory === undefined) delete process.env.PI_SKILLS_DIR; else process.env.PI_SKILLS_DIR = previousDirectory;
    if (previousAgent === undefined) delete process.env.PI_CODING_AGENT_DIR; else process.env.PI_CODING_AGENT_DIR = previousAgent;
  });
  const { POST } = await jiti.import("../app/api/skills/install/route.ts");
  const { loadSkillsWithInstallInfo } = await jiti.import("./skills-service.ts");
  const request = (headers) => new Request("http://127.0.0.1/api/skills/install", { method: "POST", headers, body: JSON.stringify({ package: source, scope: "global", cwd: source, directory: source }) });
  assert.equal((await POST(request({ host: "127.0.0.1", "content-type": "application/json", origin: "https://untrusted.example" }))).status, 403);
  const result = await POST(request({ host: "127.0.0.1", "content-type": "application/json" }));
  assert.equal(result.status, 200, JSON.stringify(await result.clone().json()));
  assert.equal((await result.json()).directory, directory, "caller scope/cwd/directory must not redirect installation");
  assert.equal(readFileSync(join(directory, "native-install-fixture", "reference.txt"), "utf8"), "supporting content");
  assert.equal(existsSync(join(source, ".pi")), false);
  const inventory = await loadSkillsWithInstallInfo(source);
  assert.equal(inventory.installDirectory, directory);
  const installed = inventory.skills.find((skill) => skill.name === "native-install-fixture");
  assert.equal(installed.sourceInfo.source, "pi-own-local-skills");
  assert.equal(installed.install.directory, directory);
});
