import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { createJiti } from "jiti";
import { createFauxCore, fauxAssistantMessage } from "@earendil-works/pi-ai";

test("learner settings rebuild before the first reply, load the exact prompt, preserve boundaries and recover", async (t) => {
  const root = mkdtempSync(join(tmpdir(), "pi-learner-settings-"));
  const env = { PI_CODING_AGENT_DIR: join(root, "agent"), PI_LEARNING_HARNESS_DIR: join(root, "harness"), PI_CODING_AGENT_SESSION_DIR: join(root, "sessions"), ANTHROPIC_API_KEY: "offline-fixture" };
  const saved = Object.fromEntries(Object.keys(env).map((key) => [key, process.env[key]]));
  Object.assign(process.env, env);
  mkdirSync(env.PI_CODING_AGENT_DIR, { recursive: true });
  const jiti = createJiti(import.meta.url, { tsconfigPaths: true });
  const rpc = await jiti.import("./rpc-manager.ts");
  const { getLearningHarness, bindHarnessCourse } = await jiti.import("./harness-server.ts");
  const { getSessionModeSettings, updateSessionModeSettings } = await jiti.import("./mode-settings-service.ts");
  t.after(async () => {
    for (const wrapper of globalThis.__piSessions?.values() ?? []) await wrapper.shutdown();
    globalThis.__piLearningHarness?.close(); globalThis.__piLearningHarness = undefined;
    for (const [key, value] of Object.entries(saved)) { if (value === undefined) delete process.env[key]; else process.env[key] = value; }
    rmSync(root, { recursive: true, force: true });
  });
  const harness = getLearningHarness();
  const course = await harness.publishCourseVersion("settings-course", [{ name: "course.md", kind: "markdown", mediaType: "text/markdown", content: "A variable represents an unknown value." }]);
  const started = await rpc.startRpcSession("new-fixture", "", root, { harnessCourseVersionId: course.courseVersionId });
  const bound = bindHarnessCourse(started.session.inner.sessionManager, course.courseVersionId);
  started.session.activateHarnessProfile(bound.snapshot);
  const sessionId = started.realSessionId;
  const models = await started.session.inner.modelRuntime.getAvailable();
  const target = models.find((model) => model.id !== started.session.inner.model.id);
  assert.ok(target);
  await started.session.send({ type: "set_model", provider: target.provider, modelId: target.id });
  let live = rpc.getRpcSession(sessionId);
  assert.notEqual(live, started.session);
  assert.equal(live.inner.model.id, target.id);
  let current = await getSessionModeSettings(sessionId);
  assert.ok(current.skills.some((skill) => skill.loaded), "learner Skills must be visible before a model run");
  const prompt = "Explain this course with short examples and ask one useful check.";
  const disabledSkill = current.skills.find((skill) => skill.enabled && !skill.required);
  const request = { sessionId, expectedSnapshotId: current.snapshotId, idempotencyKey: "edit-learner", settingsPatch: { systemPrompt: prompt, skills: [{ id: disabledSkill.id, enabled: false }] } };
  current = await updateSessionModeSettings(request);
  assert.equal(current.systemPrompt, prompt);
  assert.equal(current.skills.find((skill) => skill.id === disabledSkill.id).loaded, false);
  assert.equal(harness.getCurrentSession(sessionId).binding.courseVersionId, course.courseVersionId);
  assert.equal(harness.getCurrentSession(sessionId).binding.role, "student");
  await assert.rejects(updateSessionModeSettings({ ...request, idempotencyKey: "bad-tools", expectedSnapshotId: current.snapshotId, settingsPatch: { tools: ["bash"] } }), /Learner tools/);
  const file = rpc.getRpcSession(sessionId).sessionFile;
  await rpc.getRpcSession(sessionId).shutdown();
  live = (await rpc.startRpcSession(sessionId, file, undefined)).session;
  assert.equal(live.inner.model.id, target.id);
  assert.ok((await live.send({ type: "get_state" })).systemPrompt.includes(prompt));
  const practice = harness.prepareProfileTransition({ sessionId, targetProfileId: "practice", expectedSnapshotId: current.snapshotId, idempotencyKey: "practice" });
  live = await rpc.warmSwitchHarnessProfile(sessionId, practice);
  assert.ok(!live.inner.agent.state.systemPrompt.includes(prompt));
  const returnToTutor = harness.prepareProfileTransition({ sessionId, targetProfileId: bound.snapshot.profileId, expectedSnapshotId: practice.snapshot.resourceSnapshotId, idempotencyKey: "return" });
  live = await rpc.warmSwitchHarnessProfile(sessionId, returnToTutor);
  assert.ok(live.inner.agent.state.systemPrompt.includes(prompt));
  const faux = createFauxCore({});
  faux.setResponses([fauxAssistantMessage("unpublished fixture")]);
  let captured;
  live.inner.agent.streamFunction = (model, context, options) => { captured = context.systemPrompt; return faux.stream(model, context, options); };
  await live.inner.prompt("What is a variable?");
  assert.ok(captured.includes(prompt), "the next real SDK turn must receive the edited mode prompt");
  assert.ok(captured.includes("submit_grounded_answer"), "the grounded publication instruction must survive prompt composition");
  assert.ok(!captured.includes(disabledSkill.content), "disabled Skill text must not leak through an earlier instruction snapshot");
  const nextModel = models.find((model) => model.id !== live.inner.model.id);
  await live.send({ type: "set_model", provider: nextModel.provider, modelId: nextModel.id });
  const { SessionManager } = await jiti.import("@earendil-works/pi-coding-agent");
  assert.deepEqual(SessionManager.open(file).buildSessionContext().model, { provider: nextModel.provider, modelId: nextModel.id }, "after a reply, the learner selector must read back the new model from the transcript");
});
