import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { createJiti } from "jiti";

test("project conversations share course state and defaults, without copying chat or changing independent sessions", async (t) => {
  const root = mkdtempSync(join(tmpdir(), "pi-project-conversations-"));
  const cwd = join(root, "work"); mkdirSync(cwd);
  const env = { PI_LEARNING_HARNESS_DIR: join(root, "data"), PI_CODING_AGENT_DIR: join(root, "agent"), PI_MODE_PACK_STORE_PATH: join(root, "packs.json") };
  const saved = Object.fromEntries(Object.keys(env).map((key) => [key, process.env[key]])); Object.assign(process.env, env);
  const originalFetch = globalThis.fetch;
  globalThis.fetch = async () => { throw new Error("No model or network calls allowed"); };
  t.after(() => { globalThis.__piLearningHarness?.close(); globalThis.__piLearningHarness = undefined; globalThis.fetch = originalFetch; for (const [key, value] of Object.entries(saved)) { if (value === undefined) delete process.env[key]; else process.env[key] = value; } rmSync(root, { recursive: true, force: true }); });
  const jiti = createJiti(import.meta.url, { tsconfigPaths: true });
  const { GET, POST } = await jiti.import("../app/api/projects/route.ts");
  const { getLearningHarness } = await jiti.import("./harness-server.ts");
  const { ModePackStore } = await jiti.import("./mode-pack-store.ts");
  const { reviseModePackSettings, modeSystemPrompt } = await jiti.import("../../../packages/profile-resource-host/src/index.ts");
  const { createDefaultCourseBuilderProject } = await jiti.import("./course-builder-defaults.ts");
  const rpc = await jiti.import("./rpc-manager.ts");
  const { resolveSessionPath } = await jiti.import("./session-reader.ts");
  const { SessionManager } = await jiti.import("@earendil-works/pi-coding-agent");
  async function request(body, status = 200) { const response = await POST(new Request("http://127.0.0.1:30141/api/projects", { method: "POST", headers: { host: "127.0.0.1:30141", "content-type": "application/json" }, body: JSON.stringify(body) })); const value = await response.json(); assert.equal(response.status, status, JSON.stringify(value)); return value; }
  const host = getLearningHarness().courseBuilder;
  const project = host.createProject(createDefaultCourseBuilderProject(), "2026-09-06T00:00:00.000Z");
  const resolved = await new ModePackStore().resolve("course-builder", cwd);
  const snapshot = reviseModePackSettings(resolved.snapshot, { provider: "openai-codex", model: "gpt-6-astra", systemPrompt: "Teach this course with the shared teacher instructions.", skills: [{ id: "education.feynman-teach-back", enabled: false }] }, resolved.inventory.catalog);
  const old = rpc.createPersistedGenericSession(cwd, "Original course chat", snapshot);
  const originalManager = SessionManager.open(await resolveSessionPath(old));
  originalManager.appendMessage({ role: "user", content: "This conversation's private explanation must not enter a new chat.", timestamp: Date.now() });
  assert.equal(SessionManager.open(await resolveSessionPath(old)).buildSessionContext().messages.length, 1);
  host.bindSession(old, project.projectId);
  const before = host.getSnapshotForSession(old);
  const input = { action: "new_conversation", projectId: project.projectId, title: "Lesson 2", requestId: "lesson-2" };
  const created = await request(input);
  assert.notEqual(created.sessionId, old);
  assert.equal((await request(input)).sessionId, created.sessionId, "retry must not create another empty chat");
  await request({ ...input, title: "Changed title" }, 409);
  assert.deepEqual(host.getSnapshotForSession(created.sessionId), before);
  const manager = SessionManager.open(await resolveSessionPath(created.sessionId));
  assert.deepEqual(manager.buildSessionContext().messages, []);
  assert.equal(manager.getHeader().parentSession, undefined);
  assert.equal(manager.getSessionName(), "Lesson 2");
  const childSnapshot = (await rpc.getGenericModePackStatus(created.sessionId)).runtime.binding.snapshot;
  assert.equal(modeSystemPrompt(childSnapshot), "Teach this course with the shared teacher instructions.");
  assert.equal(childSnapshot.model, "gpt-6-astra");
  assert.equal(childSnapshot.resources.some((item) => item.id === "education.feynman-teach-back" && item.enabled), false);
  assert.equal(rpc.getRpcSession(created.sessionId), undefined, "creation must not start a model");
  host.updateProject(project.projectId, { ...createDefaultCourseBuilderProject(), title: "Updated shared course" }, before.project.revision);
  assert.equal(host.getSnapshotForSession(created.sessionId).project.title, "Updated shared course");
  const independent = rpc.createPersistedGenericSession(cwd, "Outside");
  assert.equal(host.getProjectForSession(independent), null);
  assert.equal((await rpc.getGenericModePackStatus(independent)).runtime.binding, null);
  const folder = await request({ action: "create", requestId: "writing", title: "Writing", cwd, sourceSessionId: independent });
  await request({ action: "move", projectId: folder.id, sessionId: independent });
  const savedDefaults = await request({ action: "save_defaults", projectId: folder.id, sessionId: independent, expectedRevision: 1 });
  assert.equal(savedDefaults.revision, 2);
  await request({ action: "save_defaults", projectId: folder.id, sessionId: independent, expectedRevision: 1 }, 409);
  await request({ action: "save_defaults", projectId: folder.id, sessionId: old, expectedRevision: 2 }, 400);
  const generic = await request({ action: "new_conversation", projectId: folder.id, title: "Draft", requestId: "writing-chat" });
  assert.match(generic.href, /^\/\?session=/);
  assert.equal(host.getProjectForSession(generic.sessionId), null);
  assert.equal((await rpc.getGenericModePackStatus(generic.sessionId)).runtime.binding.snapshot.profileId, "general");
  await request({ action: "move", projectId: null, sessionId: independent });
  const list = await (await GET(new Request("http://127.0.0.1:30141/api/projects", { headers: { host: "127.0.0.1:30141" } }))).json();
  assert.equal(list.conversations.filter((item) => item.projectId === project.projectId).length, 2);
  assert.equal(list.conversations.find((item) => item.id === independent).projectId, null);
  const { ProjectWorkspaceHost } = await jiti.import("../../../packages/learning-harness/src/project-workspaces.ts");
  const { DatabaseSync } = await import("node:sqlite");
  const reopenedDb = new DatabaseSync(join(root, "data", "learning-harness.sqlite"));
  try { const reopened = new ProjectWorkspaceHost(reopenedDb); assert.equal(reopened.get(folder.id).revision, 2); assert.ok(reopened.members().some((item) => item.sessionId === created.sessionId)); }
  finally { reopenedDb.close(); }
  const denied = await POST(new Request("http://127.0.0.1:30141/api/projects", { method: "POST", headers: { origin: "https://untrusted.example", host: "127.0.0.1:30141" }, body: JSON.stringify(input) }));
  assert.equal(denied.status, 403);
});
