import assert from 'node:assert/strict';
import test from 'node:test';
import {createHash} from 'node:crypto';
import {mkdtemp,mkdir,writeFile,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createJiti} from 'jiti';
const jiti=createJiti(import.meta.url,{tsconfigPaths:true});
const {assertStudyExplanationGraph}=await jiti.import('./study-workflow-admission.ts');
const {STUDY_WORKFLOW_AUTHOR_SCHEMA,studyWorkflowToolContracts}=await jiti.import('./study-workflow-domain.ts');
function graph(){return {id:'study-explanation',skill_policy:{mode:'strict',implicit:'deny',ambient_allow:[],shadowed_skill_paths:[]},requirements:{providers:['writer'],tools:['study_task_context','study_response_commit'],mcp_servers:[],executables:[]},nodes:[{id:'begin',type:'start'},{id:'activity_001',type:'tool',executor:{kind:'tool',tool:'study_task_context'},input_bindings:{taskId:'/inputs/taskId'}},{id:'activity_002',type:'agent',executor:{kind:'provider',provider_id:'writer'},access:'read_only',subagent_count:'auto',input_bindings:{question:'/inputs/question',context:'/nodes/activity_001/output/context'},outputs_schema:STUDY_WORKFLOW_AUTHOR_SCHEMA},{id:'activity_003',type:'tool',executor:{kind:'tool',tool:'study_response_commit'},input_bindings:{taskId:'/inputs/taskId',requestId:'/inputs/requestId',bindingSha256:'/nodes/activity_001/output/bindingSha256',answer:'/nodes/activity_002/output/answer'},completion_contract:{fail_on_false:['succeeded']}},{id:'end',type:'end'}],edges:[['begin','activity_001'],['activity_001','activity_002'],['activity_002','activity_003'],['activity_003','end']].map(([source,target])=>({source,target})),finalization:{required:true,node_id:'activity_003'}};}
test('authoritative pinned graph permits one compiler-named readonly explanation and rejects permission/role/identity bypass',()=>{assert.equal(assertStudyExplanationGraph(graph()),'activity_003');for(const alter of [g=>g.nodes[2].access='bounded_write',g=>g.nodes[2].executor.kind='main',g=>g.nodes[2].fanout={input:'files'},g=>g.skill_policy.mode='cooperative',g=>g.requirements.mcp_servers=['private-server'],g=>g.nodes[2].skill_policy={mode:'cooperative',implicit:'allow'},g=>g.nodes[2].outputs_schema={type:'object',properties:{answer:{type:'string'},noteId:{type:'string'}}},g=>g.nodes[3].input_bindings.requestId='/nodes/activity_002/output/requestId',g=>g.nodes[2].input_bindings.fullHistory='/inputs/history',g=>g.edges.push({source:'begin',target:'activity_003'}),g=>g.finalization.node_id='activity_002']){const g=structuredClone(graph());alter(g);assert.throws(()=>assertStudyExplanationGraph(g),/closure denied/);}});
test('compiler worker_read conventions resolve exactly one author and require exactly the two Study tools',()=>{
 for(const quantity of [undefined,'auto',1]){const g=graph();g.nodes[2].subagent_count=quantity;g.requirements.tools.reverse();assert.equal(assertStudyExplanationGraph(g),'activity_003');}
 for(const quantity of [0,2,'1','2','parallel',null]){const g=graph();g.nodes[2].subagent_count=quantity;assert.throws(()=>assertStudyExplanationGraph(g),/readonly provider/);}
 for(const tools of [[],['study_task_context'],['study_task_context','study_task_context'],['study_task_context','study_response_commit','bash'],['study_task_context','private_teacher_tool']]){const g=graph();g.requirements.tools=tools;assert.throws(()=>assertStudyExplanationGraph(g),/registered Study Host tools/);}
 for(const quantity of [undefined,'auto',1]){const g=graph();g.nodes[2].subagent_count=quantity;g.nodes[2].fanout={input:'sources'};assert.throws(()=>assertStudyExplanationGraph(g),/readonly provider/);}
 const unbounded=graph();unbounded.nodes[2].outputs_schema={type:'object',additionalProperties:false,required:['answer'],properties:{answer:{type:'string'}}};assert.throws(()=>assertStudyExplanationGraph(unbounded),/bounded semantic answer/);
});
test('real Study session prepares, admits, commits and projects a canonical note with arbitrary compiler IDs',async(t)=>{
 const cwd=await mkdtemp(join(tmpdir(),'study-workflow-service-')),environment={PI_LEARNING_HARNESS_DIR:join(cwd,'data'),PI_CODING_AGENT_DIR:join(cwd,'agent'),PI_MODE_PACK_STORE_PATH:join(cwd,'packs.json')},previous=Object.fromEntries(Object.keys(environment).map(key=>[key,process.env[key]]));Object.assign(process.env,environment);await mkdir(environment.PI_CODING_AGENT_DIR,{recursive:true});
 const fetchBefore=globalThis.fetch;globalThis.fetch=async()=>{throw new Error('No model or network call in Study Workflow fixture');};
 t.after(async()=>{globalThis.__piLearningHarness?.close();globalThis.__piLearningHarness=undefined;globalThis.__piStudyWorkflowTasks=undefined;globalThis.__piStudyWorkflowControls=undefined;globalThis.__piStudyWorkflowScopes=undefined;globalThis.__piStudyWorkflowStarting=undefined;globalThis.fetch=fetchBefore;for(const [key,value]of Object.entries(previous)){if(value===undefined)delete process.env[key];else process.env[key]=value;}await rm(cwd,{recursive:true,force:true});});
 const {getLearningHarness}=await jiti.import('./harness-server.ts'),{ModePackStore}=await jiti.import('./mode-pack-store.ts'),{createPersistedGenericSession}=await jiti.import('./rpc-manager.ts'),{studyContext}=await jiti.import('./study-research-service.ts'),{contentHash}=await jiti.import('../../../packages/harness-core/src/index.ts'),tasks=await jiti.import('./study-workflow-tasks.ts');
 const snapshot=(await new ModePackStore().resolve('study-research.study',cwd)).snapshot,sessionId=createPersistedGenericSession(cwd,'Scoped explanation',snapshot),otherId=createPersistedGenericSession(cwd,'Other learner',snapshot),harness=getLearningHarness();harness.projectWorkspaces.create({id:'paper',title:'Study paper',cwd,defaults:snapshot,courseProjectId:null});harness.projectWorkspaces.move(sessionId,'paper');harness.projectWorkspaces.move(otherId,'paper');const {host,scope}=await studyContext(sessionId);await writeFile(join(cwd,'paper.tex'),'Linearity of expectation makes sample means unbiased.');host.registerSource(scope,{sourceRoot:cwd,relativePath:'paper.tex',kind:'tex',sourceRole:'primary',diagnostics:[],contentHash:`sha256:${createHash('sha256').update('Linearity of expectation makes sample means unbiased.').digest('hex')}`,parser:'fixture',chunks:[{ordinal:1,locator:JSON.stringify({line:1}),text:'Linearity of expectation makes sample means unbiased.'}]},0);
 const pinnedTools=studyWorkflowToolContracts().map(contract=>({...contract,identity:{...contract.identity,version:'previous-program',sha256:'e'.repeat(64)}}));
 let run,args;const release=tasks.registerStudyWorkflowControl(sessionId,async(operation,input)=>{if(operation==='list')return [{id:'study-explanation',status:'ready',enabled:true,revision_hash:'revision-fixture',validation:{valid:true}}];if(operation==='run'){args=input;await tasks.assertStudyWorkflowRunScope(sessionId,{...input,workflow:graph(),host_tool_contracts:pinnedTools});run={run_id:input.run_id,main_actor:sessionId,workflow_id:input.workflow_id,inputs:input.inputs,permissions:{workspace:input.workspace},status:'running',updated_at:new Date().toISOString(),nodes:{}};return {run_id:input.run_id};}if(operation==='get'){if(!run||input.run_id!==run.run_id)throw new Error('Unknown exact Run');return run;}throw new Error('Unexpected operation');});t.after(release);
 await assert.rejects(tasks.prepareStudyWorkflowTask(sessionId,{question:'Explain',sourceIds:['unknown-source']}),/current sources/);const prepared=await tasks.prepareStudyWorkflowTask(sessionId,{question:'Explain why a sample mean is unbiased.'});assert.equal(prepared.sourceCount,1);await assert.rejects(tasks.startStudyWorkflowTask(otherId,prepared.taskId),/unavailable/);const started=await tasks.startStudyWorkflowTask(sessionId,prepared.taskId);assert.equal(started.started,true);assert.equal(args.access,'read_only');await assert.rejects(tasks.startStudyWorkflowTask(sessionId,prepared.taskId),/already bound/);await assert.rejects(tasks.assertStudyWorkflowRunScope(sessionId,{...args,workflow:graph(),host_tool_contracts:studyWorkflowToolContracts(),workspace:cwd}),/privately bound/);
 const registry=tasks.studyWorkflowRegistry(sessionId),context={run_id:started.runId,node_id:'activity_001',attempt_id:'context',workspace:args.workspace},contextResult=await registry.study_task_context.execute({input:{taskId:prepared.taskId},context});assert.equal(contextResult.exit_code,0,contextResult.diagnostic);const answer='At source line 1, linearity implies E[(X1 + … + Xn)/n] = μ. Independence is unnecessary for this expectation statement.';const committed=await registry.study_response_commit.execute({input:{taskId:prepared.taskId,requestId:args.inputs.requestId,bindingSha256:contextResult.output.bindingSha256,answer},context:{...context,node_id:'activity_003',attempt_id:'commit'}});assert.equal(committed.exit_code,0,committed.diagnostic);run.status='succeeded';run.nodes.activity_003={status:'succeeded',output:committed.output};const result=await tasks.statusStudyWorkflowTask(sessionId,prepared.taskId);assert.equal(result.response.answer,answer);assert.equal(host.getKnowledge(scope).notes.length,1);assert.equal(result.response.noteId,committed.output.note.noteId);assert.equal(JSON.parse(await readFile(join(globalThis.__piStudyWorkflowTasks.get(prepared.taskId).record.journalDirectory,'host-task.json'),'utf8')).commitNodeId,'activity_003');
 const unknown=registry.study_response_commit.cancel({context:{...context,run_id:'unknown-run'}});await assert.rejects(unknown,/admission history/);
});
