import assert from 'node:assert/strict';
import { mkdtempSync,mkdirSync,rmSync } from 'node:fs';
import { join,resolve } from 'node:path';
import test from 'node:test';
import { createJiti } from 'jiti';

test('real Course Builder lesson receives an independent Study copy; browser confirmation, scope, revisions and repeat requests stay bound',async(t)=>{
 const parent=resolve('.artifacts/study-research/teaching');mkdirSync(parent,{recursive:true});const root=mkdtempSync(join(parent,'service-'));
 const environment={PI_LEARNING_HARNESS_DIR:join(root,'data'),PI_CODING_AGENT_DIR:join(root,'agent'),PI_MODE_PACK_STORE_PATH:join(root,'packs.json')};const previous=Object.fromEntries(Object.keys(environment).map(k=>[k,process.env[k]]));Object.assign(process.env,environment);
 const fetchBefore=globalThis.fetch;globalThis.fetch=async()=>{throw new Error('No network in teaching fixture');};
 t.after(()=>{globalThis.__piLearningHarness?.close();globalThis.__piLearningHarness=undefined;globalThis.fetch=fetchBefore;for(const [k,v] of Object.entries(previous)){if(v===undefined)delete process.env[k];else process.env[k]=v;}rmSync(root,{recursive:true,force:true});});
 const jiti=createJiti(import.meta.url,{tsconfigPaths:true});
 const {getLearningHarness}=await jiti.import('./harness-server.ts');
 const {ModePackStore}=await jiti.import('./mode-pack-store.ts');
 const {createPersistedGenericSession}=await jiti.import('./rpc-manager.ts');
 const {studyContext}=await jiti.import('./study-research-service.ts');
 const {contentHash}=await jiti.import('../../../packages/harness-core/src/index.ts');
 const {transferStudyTeachingCopy,courseStudyCopies,approveCourseStudyCopy,studyTeachingState}=await jiti.import('./study-teaching-service.ts');
 const {POST}=await jiti.import('../app/api/study-research/teaching/route.ts');
 const harness=getLearningHarness(),packs=new ModePackStore(),studySnapshot=(await packs.resolve('study-research.study',root)).snapshot;
 const sessionId=createPersistedGenericSession(root,'Study teaching origin',studySnapshot);harness.projectWorkspaces.create({id:'teaching-study',title:'Study',cwd:root,defaults:studySnapshot,courseProjectId:null});harness.projectWorkspaces.move(sessionId,'teaching-study');
 const {scope,host}=await studyContext(sessionId);
 const source=host.registerSource(scope,{sourceRoot:root,relativePath:'source.tex',kind:'tex',sourceRole:'primary',diagnostics:[],contentHash:contentHash('source'),parser:'fixture',chunks:[{ordinal:1,locator:JSON.stringify({line:1}),text:'A scalar coordinate.'}]},0);
 host.commitKnowledgeChange(scope,{nodes:[],notes:[{author:'user',body:'Scalar coordinate note',sourceId:source.sourceId,sourceHash:source.contentHash,nodeLocalKeys:[]}],relations:[]},1);
 const note=host.getKnowledge(scope).notes[0];
 const projectInput={courseId:'teaching-fixture',title:'Teaching fixture',weeks:1,sessionsPerWeek:1,minutesPerSession:50,audience:'Professional',language:'English',goals:['Understand coordinate'],beamerProfile:{aspectRatio:'169',fontSize:11,theme:'default',author:'Teacher',institute:'Local',language:'English',overlayPolicy:'allow',referencesPolicy:'optional',backupSlides:0,speakerNotes:false,preamble:null}};
 const course=harness.courseBuilder.createProject(projectInput),courseSnapshot=(await packs.resolve('course-builder',root)).snapshot;
 const courseSessionId=createPersistedGenericSession(root,'Teaching target',courseSnapshot);harness.courseBuilder.bindSession(courseSessionId,course.projectId);
 const [material]=harness.courseBuilder.importMaterials(courseSessionId,[{name:'notes.md',kind:'markdown',sourceBytes:Buffer.from('coordinate'),extractedText:'coordinate'}],1);
 const semester=harness.courseBuilder.saveSemesterPlan(courseSessionId,{title:'Semester',rationale:'Explore coordinates',sessions:[{week:1,session:1,title:'Coordinate',objectives:['Understand coordinate'],prerequisites:[],topics:['Coordinate'],materialIds:[material.materialId],activities:['Explore'],understandingEvidence:['Explain'],assessment:null,homework:null,courseGoalsCovered:['Understand coordinate'],revisits:[],visualOpportunities:['Move a point']}]},0);
 harness.courseBuilder.reviewSemesterPlan(courseSessionId,semester.semesterPlanId,1,'approve','Fixture teacher approved');
 const lessonDraft={week:1,session:1,title:'Coordinate',objectives:['Understand coordinate'],prerequisites:[],misconceptions:[],segments:[{minutes:45,title:'Explore',teacherAction:'Explain',learnerAction:'Explore',checkForUnderstanding:'Discuss'}],examples:['Point'],exercises:[],materialIds:[material.materialId],visualRequests:[],notes:[]};
 const lesson=harness.courseBuilder.saveLessonPlan(courseSessionId,lessonDraft,0,1);harness.courseBuilder.reviewLessonPlan(courseSessionId,lesson.lessonPlanId,1,'approve','Fixture teacher approved');
 const input={sessionId,expectedPhaseRevision:1,courseSessionId,expectedCourseRevision:2,lessonPlanId:lesson.lessonPlanId,expectedLessonRevision:1,week:1,session:1,kind:'note',id:note.noteId,revision:note.revision,hash:note.contentHash,requestId:crypto.randomUUID()};
 assert.equal((await POST(new Request('http://127.0.0.1:30141/api/study-research/teaching',{method:'POST',body:JSON.stringify(input)}))).status,403);
 await assert.rejects(transferStudyTeachingCopy({...input,lessonPlanId:'fake-lesson'}),/lesson|Lesson/);
 await assert.rejects(transferStudyTeachingCopy({...input,session:2}),/slot|session|lesson/i);
 await assert.rejects(transferStudyTeachingCopy({...input,expectedCourseRevision:1}),/revision changed/);
 const copied=await transferStudyTeachingCopy(input);assert.equal(copied.replay,false);assert.equal((await transferStudyTeachingCopy(input)).replay,true);
 await assert.rejects(transferStudyTeachingCopy({...input,hash:contentHash('other')}),/reused with different/);
 assert.equal((await studyContext(sessionId)).scope.projectId,'teaching-study');assert.equal(harness.courseBuilder.getSnapshotForSession(sessionId),null);
 const state=await courseStudyCopies(courseSessionId),entry=state.copies[0];assert.equal(state.copies.length,1);assert.equal(entry.approved,false);assert.equal(entry.canApprove,true);assert.equal(entry.copy.payload.note.body,note.body);assert.equal(entry.copy.owner.projectId,course.projectId);
 await assert.rejects(approveCourseStudyCopy({sessionId:courseSessionId,materialId:entry.materialId,copyHash:entry.copy.contentHash,lessonRevision:1,confirmed:false}),/Explicit teacher/);
 await approveCourseStudyCopy({sessionId:courseSessionId,materialId:entry.materialId,copyHash:entry.copy.contentHash,lessonRevision:1,confirmed:true});assert.equal((await courseStudyCopies(courseSessionId)).copies[0].approved,true);
 const outsider=harness.courseBuilder.createProject({...projectInput,courseId:'other'}),outsideSession=createPersistedGenericSession(root,'Other',courseSnapshot);harness.courseBuilder.bindSession(outsideSession,outsider.projectId);
 assert.deepEqual((await courseStudyCopies(outsideSession)).copies,[]);
 await assert.rejects(approveCourseStudyCopy({sessionId:outsideSession,materialId:entry.materialId,copyHash:entry.copy.contentHash,lessonRevision:1,confirmed:true}),/changed before approval/);
 host.commitKnowledgeChange(scope,{nodes:[],notes:[{author:'user',body:'A new origin note',sourceId:source.sourceId,sourceHash:source.contentHash,nodeLocalKeys:[]}],relations:[]},2);
 assert.equal((await courseStudyCopies(courseSessionId)).copies[0].copy.contentHash,entry.copy.contentHash);
 harness.courseBuilder.saveLessonPlan(courseSessionId,{...lessonDraft,title:'Revised teaching lesson'},1,1);
 assert.equal((await courseStudyCopies(courseSessionId)).copies[0].approved,false);
 assert.equal((await studyTeachingState(sessionId)).items.filter(i=>i.kind==='note').length,2);
});
