import { Type } from "typebox";
import { registerBundledDomainWorkflowInstaller } from "./bundled-domain-workflows";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { STUDY_WORKFLOW_TOOL_IDENTITIES } from "./study-workflow-domain";
import { cancelStudyWorkflowTask, listStudyWorkflowTasks, prepareStudyWorkflowTask, registerStudyWorkflowControl, restoreStudyWorkflowTasks, startStudyWorkflowTask, statusStudyWorkflowTask, studyWorkflowRegistry, STUDY_WORKFLOW_ID, type StudyWorkflowControl } from "./study-workflow-tasks";

const instructions="Use study_workflow prepare then start for a substantive explanation of the user's current question. Prepare accepts question and optional current project sourceIds; omit sourceIds to use the current primary sources. Host freezes only those sources and saves the response in Study Notes. Acknowledge the Run and end the Main turn. Do not poll, re-explain, run a raw graph/Role or initiate research, grading or quizzes. Other deterministic Study actions remain available. Status is for an explicit user request; /caw opens workflow management.";
export function registerStudyWorkflowExtension(pi:ExtensionAPI){
  let releaseControl:(()=>void)|undefined;const presented=new Set<string>();
  const bundledWorkflows=registerBundledDomainWorkflowInstaller(pi,[STUDY_WORKFLOW_ID]);
  const control=(sessionId:string):StudyWorkflowControl=>async(operation,args)=>{if(operation==="list"||operation==="run")await bundledWorkflows.ensureAvailable(sessionId);return new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error(`Study pi-CAW ${operation} timed out; inspect its saved Run before retrying`)),120000);try{pi.events.emit("pi-caw:host-command",{session_id:sessionId,operation,args,resolve:(value:unknown)=>{clearTimeout(timer);resolve(value);},reject:(error:unknown)=>{clearTimeout(timer);reject(error);}});}catch(error){clearTimeout(timer);reject(error);}});};
  const releaseTools=pi.events.on("pi-caw:host-tools",(value:unknown)=>{const request=value as {session_id:string;registry:Record<string,unknown>;execution_admission_required?:boolean};Object.assign(request.registry,studyWorkflowRegistry(request.session_id));request.execution_admission_required=true;});
  const releaseLifecycle=pi.events.on("pi-caw:run-lifecycle",(value:unknown)=>{const event=value as {run_id:string;main_actor:string;status:string;host_tool_ids?:string[]};if(event.status!=="succeeded"||!event.host_tool_ids?.includes("study_response_commit")||presented.has(event.run_id))return;
    // Presentation happens after the native Run and ledger receipt complete, outside broker effects.
    void (async()=>{const catalog=await listStudyWorkflowTasks(event.main_actor),task=catalog.tasks.find(task=>task.runId===event.run_id);if(!task)throw new Error("Completed Study Run lacks its private task");const result=await statusStudyWorkflowTask(event.main_actor,task.taskId);if(!result.response)throw new Error("Completed Study Run lacks its verified response");presented.add(event.run_id);pi.sendMessage({customType:"study-workflow-response",content:result.response.answer,display:true},{triggerTurn:false});})().catch(error=>{console.error("[study-workflow] response presentation failed",{runId:event.run_id,error});pi.sendMessage({customType:"study-workflow-error",content:`学习 Workflow 结果验证失败：${(error as Error).message}`,display:true},{triggerTurn:false});});
  });
  pi.on("session_start",async(_event,ctx)=>{await restoreStudyWorkflowTasks(ctx.sessionManager.getSessionId());releaseControl?.();releaseControl=registerStudyWorkflowControl(ctx.sessionManager.getSessionId(),control(ctx.sessionManager.getSessionId()));bundledWorkflows.start(ctx.sessionManager.getSessionId());});
  pi.on("session_shutdown",()=>{releaseControl?.();releaseTools();releaseLifecycle();bundledWorkflows.dispose();});
  pi.on("before_agent_start",()=>({message:{customType:"study-workflow-instructions",content:instructions,display:false}}));
  pi.registerTool({name:"study_workflow",label:"学习解释 Workflow",description:instructions,parameters:Type.Object({action:Type.Union([Type.Literal("prepare"),Type.Literal("start"),Type.Literal("status"),Type.Literal("cancel"),Type.Literal("list")]),question:Type.Optional(Type.String({minLength:1,maxLength:16000})),sourceIds:Type.Optional(Type.Array(Type.String({minLength:1,maxLength:256}),{maxItems:32,uniqueItems:true})),taskId:Type.Optional(Type.String({minLength:1,maxLength:256}))},{additionalProperties:false}),async execute(_id,params,signal,_update,ctx){signal?.throwIfAborted();const sessionId=ctx.sessionManager.getSessionId();let result:unknown;if(params.action==="prepare"){if(!params.question||params.taskId!==undefined)throw new Error("Prepare needs question and optional sourceIds only");result=await prepareStudyWorkflowTask(sessionId,{question:params.question,...(params.sourceIds===undefined?{}:{sourceIds:params.sourceIds})});}else if(params.action==="list"){if(params.question!==undefined||params.sourceIds!==undefined||params.taskId!==undefined)throw new Error("List accepts no selection fields");result=await listStudyWorkflowTasks(sessionId);}else{if(!params.taskId||params.question!==undefined||params.sourceIds!==undefined)throw new Error("Select the Host-returned taskId only");result=await (params.action==="start"?startStudyWorkflowTask:params.action==="status"?statusStudyWorkflowTask:cancelStudyWorkflowTask)(sessionId,params.taskId);}return {content:[{type:"text" as const,text:JSON.stringify(result)}],details:{kind:"study-workflow",action:params.action,hostToolIds:Object.keys(STUDY_WORKFLOW_TOOL_IDENTITIES)}};}});
}
