"use client";
import { Suspense, useCallback, useEffect, useRef, useState } from "react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { I18nProvider } from "@/hooks/useI18n";
import { DirectoryPicker } from "@/components/DirectoryPicker";
import { MarkdownBody } from "@/components/MarkdownBody";
import { StudyConversation } from "@/components/study/StudyConversation";
import { StudyNotes } from "@/components/study/StudyNotes";
import { StudyCodeLab } from "@/components/study/StudyCodeLab";
import { MathVisualizationPanel } from "@/components/visualization/MathVisualizationPanel";
import { WorkspaceFilePreview } from "@/components/course-builder/WorkspaceFilePreview";
import { studyRequest, studyState, type StudyListing, type StudyState } from "@/lib/study-research-client";
import type { SourceAnchor, StudyResearchHost } from "../../../../packages/study-research-host/src/index.ts";
import styles from "./study.module.css";

type SourceRead=ReturnType<StudyResearchHost['readSource']>;
function Start() {
  const router=useRouter();
  const [listing,setListing]=useState<StudyListing|null>(null);const [title,setTitle]=useState('');const [directory,setDirectory]=useState('');const [picker,setPicker]=useState(false);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [requestId]=useState(()=>crypto.randomUUID());
  useEffect(()=>{const ctrl=new AbortController();void fetch('/api/study-research',{signal:ctrl.signal}).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error);setListing(data);}).catch(e=>{if(!ctrl.signal.aborted)setError(String(e));});return()=>ctrl.abort();},[]);
  const create=async()=>{setBusy(true);setError('');try{const value=await studyRequest<{sessionId:string}>({action:'create',requestId,title,directory});router.push(`/study-research?sessionId=${encodeURIComponent(value.sessionId)}`);}catch(e){setError(String(e));setBusy(false);}};
  return <main className={styles.start}><Link href="/">返回 Pi</Link><h1>Study & Research</h1><p>先读懂并质疑，再提出可检验的研究计划。论文、教材章节和代码都可以作为资料。</p>
    <section><h2>创建学习项目</h2><label>标题<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={300}/></label><label>只读资料目录<input value={directory} onChange={e=>setDirectory(e.target.value)}/></label><button onClick={()=>setPicker(true)}>选择文件夹</button><p>建立轻量文件清单，按需读取。不运行目录里的代码或安装依赖；常见密钥、隐藏配置和符号链接跳过。</p><button disabled={busy||!title.trim()||!directory.trim()} onClick={()=>void create()}>创建项目与独立 Pi 会话</button></section>
    {picker&&<DirectoryPicker onCancel={()=>setPicker(false)} initialPath={directory||undefined} onSelect={path=>{setDirectory(path);setPicker(false);}}/>}{error&&<p role="alert">{error}</p>}
    <h2>继续已有项目</h2>{listing?.projects.map(project=><article key={project.id}><strong>{project.title}</strong><p>{project.root}</p>{listing.bindings.filter(x=>x.projectId===project.id).map(bound=><a key={bound.sessionId} href={`/study-research?sessionId=${encodeURIComponent(bound.sessionId)}`}>继续对话 {bound.sessionId.slice(0,8)} </a>)}</article>)}
  </main>;
}
function Workspace({sessionId}:{sessionId:string}) {
  const [state,setState]=useState<StudyState|null>(null);const [codeEnabled,setCodeEnabled]=useState(false);const [error,setError]=useState('');const [ready,setReady]=useState(false);const [busy,setBusy]=useState(false);const [tab,setTab]=useState('study');const [nodeId,setNodeId]=useState<string|null>(null);const [attempt,setAttempt]=useState('');const [read,setRead]=useState<SourceRead|null>(null);const [quote,setQuote]=useState('');const [preview,setPreview]=useState<{path:string;cwd?:string}|null>(null);const [requirements,setRequirements]=useState('');
  const refreshController=useRef<AbortController|null>(null);
  const refresh=useCallback(async()=>{refreshController.current?.abort();const ctrl=new AbortController();refreshController.current=ctrl;try{const value=await studyState(sessionId,ctrl.signal);if(!ctrl.signal.aborted){setState(value.state);setCodeEnabled(value.codeEnabled);}}catch(error){if(!ctrl.signal.aborted)throw error;}},[sessionId]);
  const settled=useCallback(()=>{void refresh().catch(e=>setError(String(e)));},[refresh]);
  useEffect(()=>{let stopped=false;void refresh().catch(e=>{if(!stopped)setError(String(e));});const t=setInterval(()=>{void refresh().catch(()=>{});},7000);return()=>{stopped=true;clearInterval(t);refreshController.current?.abort();};},[refresh]);
  const action=async(payload:Record<string,unknown>)=>{setBusy(true);setError('');try{await studyRequest({...payload,sessionId});await refresh();}catch(e){setError(String(e));}finally{setBusy(false);}};
  const source=async(id:string,startLine=1)=>{setError('');try{setRead(await studyRequest<SourceRead>({action:'read_source',sessionId,id,startLine}));setQuote('');}catch(e){setError(String(e));}};
  const openFile=useCallback((path:string,cwd?:string)=>setPreview({path,cwd}),[]);const closeFile=useCallback(()=>setPreview(null),[]);
  const exportNotes=()=>{if(!state)return;const md=[`# ${state.project.title}`,`Source manifest: ${state.project.manifestVersion}`,state.roadmap?.data.story??'',state.roadmap?.data.contribution??'',...(state.roadmap?.data.nodes.map(n=>`## ${n.title}\nStatus: ${n.epistemicStatus}\n${n.explanation}\nSources: ${JSON.stringify(n.sources)}\nOpen questions: ${n.openQuestions.join('; ')}`)??[]),...state.notes.map(n=>`## Note (${n.data.author}, r${n.revision})\n${n.data.body}\nAnchor: ${JSON.stringify(n.data.anchor)}`)].join('\n\n');const url=URL.createObjectURL(new Blob([md],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`${state.project.id}-study-notes.md`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  const node=state?.roadmap?.data.nodes.find(n=>n.id===nodeId);
  const anchor:SourceAnchor|null=read&&quote.trim()?{sourceId:read.sourceId,sourceHash:read.sourceHash,startLine:read.startLine,endLine:read.endLine,quote}:null;
  const task=(message:string)=>void action({action:'prompt',message:`${message}\n用户补充要求：${requirements||'无'}\n不要声称读完了未读取的内容，不要自动执行实验。`});
  return <div className={styles.workspace}><main className={styles.main}>
    <header><a href="/study-research">项目列表</a> · <a href={`/?session=${encodeURIComponent(sessionId)}`}>原 Pi 会话</a> · <a href="/projects">所有项目</a><h1>{state?.project.title??'Study & Research'}</h1><p>Study 是逐步形成可核查的理解；Research 是提出待批准的实验。不是正确性证书。</p></header>
    {error&&<p role="alert">{error}</p>}{state?<>
      <button onClick={exportNotes}>导出学习地图与笔记 Markdown</button><nav aria-label="学习工作区">{[['study','阅读地图'],['notes','笔记'],['research','研究方案'],['code','代码实验台'],['visual','2D / 3D 可视化']].map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</nav>
      <details><summary>资料目录与版本 · {state.project.sources.length} 文件</summary><p>{state.project.root} · manifest v{state.project.manifestVersion}</p><button disabled={busy} onClick={()=>{if(confirm('重新扫描会使现有地图和实验过期，但保留历史笔记。继续？'))void action({action:'reindex',expectedRevision:state.project.revision});}}>重新扫描目录</button><ul>{state.project.sources.map(entry=><li key={entry.id}><button onClick={()=>void source(entry.id)}>{entry.path}</button> <button onClick={()=>openFile(`${state.project.root.replace(/[\\/]$/,'')}/${entry.path}`,state.project.root)}>查看原文件</button> <small>{entry.size} bytes</small></li>)}</ul></details>
      {read&&<section><h3>来源 · {read.sourceId}</h3><small>提取文本行 {read.startLine}–{read.endLine} / {read.totalLines}，不是 PDF 页码 · {read.sourceHash}</small><pre className={styles.source}>{read.text.split('\n').map((line,i)=>`${read.startLine+i}  ${line}`).join('\n')}</pre><details><summary>数学 Markdown 阅读视图</summary><MarkdownBody>{read.text}</MarkdownBody></details><button disabled={read.startLine===1} onClick={()=>void source(read.sourceId,Math.max(1,read.startLine-80))}>上一段</button><button disabled={!read.nextLine} onClick={()=>void source(read.sourceId,read.nextLine??1)}>下一段</button><input aria-label="笔记引用原文" placeholder="粘贴本段中要注释的原文（最多 2000 字符）" maxLength={2000} value={quote} onChange={e=>setQuote(e.target.value)}/><button onClick={()=>setTab('notes')}>为该段写笔记</button></section>}
      {(tab==='study'||tab==='research')&&<section><label>本次范围／补充要求<input value={requirements} onChange={e=>setRequirements(e.target.value)} placeholder="例如只学第 2 节；先解释定义，再看证明。"/></label><button disabled={!ready||busy} onClick={()=>task('Use study_research schema/state and read the relevant sources. Save a bounded roadmap covering minimum background, notation and definitions, main contribution/story, proof/code dependencies, concrete checks and unresolved issues. Treat author claims critically. For a long book explicitly scope a chapter. Then show what is ready and what remains unread.')}>生成／修订阅读地图</button>{tab==='research'&&<button disabled={!ready||busy||!state.roadmap||state.roadmap.stale} onClick={()=>task('Read the current roadmap, sources and questions. Propose the most promising few research directions with falsifiable hypotheses, stronger simpler alternatives, feasibility, risks and minimum evidence. Save proposals, then a minimal experiment plan for the best justified direction. Do not claim novelty without literature evidence. Stop for user discussion and approval.')}>提出方向与实验草案</button>}</section>}
      {tab==='study'&&<section>{!state.roadmap?<p>尚无地图。先读取资料，再请求 Agent 拆解；不能把一段聊天摘要当作已保存的地图。</p>:<>
        {state.roadmap.stale&&<p role="alert">地图基于旧资料清单，请修订。历史内容保留但不是当前核查结果。</p>}<h2>文章在讲什么</h2><MarkdownBody>{state.roadmap.data.story}</MarkdownBody><h3>主张与贡献</h3><MarkdownBody>{state.roadmap.data.contribution}</MarkdownBody><p>范围：{state.roadmap.data.scope}</p><h3>尚未解决</h3><ul>{state.roadmap.data.uncertainties.map((x,i)=><li key={i}>{x}</li>)}</ul>
        <label>进入一个知识点<select value={nodeId??''} onChange={e=>setNodeId(e.target.value||null)}><option value="">选择知识点</option>{state.roadmap.data.nodes.map(n=><option key={n.id} value={n.id}>{n.kind} · {n.title}</option>)}</select></label>
        {node&&<article><h2>{node.title}</h2><p>核查记录：{node.epistemicStatus}（不是形式化证明认证）</p><p>先备：{node.dependsOn.join(' → ')||'无'} · 为什么需要：{node.whyNeeded}</p><MarkdownBody>{node.explanation}</MarkdownBody><h4>理解检查</h4><ul>{node.checks.map((x,i)=><li key={i}>{x}</li>)}</ul><h4>疑点与待核查</h4><ul>{node.openQuestions.map((x,i)=><li key={i}>{x}</li>)}</ul>{node.sources.map((a,i)=><button key={i} onClick={()=>void source(a.sourceId,a.startLine)}>来源 {a.sourceId} L{a.startLine}–{a.endLine}</button>)}<button disabled={!ready||busy||state.roadmap.stale} onClick={()=>task(`Read current node ${node.id} and its exact sources. Explain it interactively: intuition, notation, exact assumptions and step-by-step proof or actual code trace. Distinguish paper errors, missing justification and your own uncertainty. Ask one useful check, do not replace the learner's attempt.`)}>和我逐步讲解这一点</button>
          <textarea aria-label="我的理解与尝试" value={attempt} onChange={e=>setAttempt(e.target.value)} placeholder="用自己的话解释、写一个例子或记录卡点。" rows={4}/><button disabled={!attempt.trim()||busy||state.roadmap.stale} onClick={()=>void action({action:'progress',nodeId:node.id,roadmapRevision:state.roadmap!.revision,stage:'learning',attempt})}>记录我正在学习</button><button disabled={!attempt.trim()||busy||state.roadmap.stale} onClick={()=>void action({action:'progress',nodeId:node.id,roadmapRevision:state.roadmap!.revision,stage:'can-explain',attempt})}>记录我能解释（自评）</button>
        </article>}<details><summary>阅读地图与实际读过的范围</summary><pre>{JSON.stringify({reads:state.reads,map:state.roadmap},null,2)}</pre></details>
      </>}</section>}
      {tab==='notes'&&<StudyNotes sessionId={sessionId} state={state} selectedNode={nodeId} anchor={anchor} onSaved={settled}/>}
      {tab==='research'&&<section><h2>研究方向（未经新颖性认证）</h2>{state.proposals.map(p=><article key={p.id}><h3>{p.data.title} · r{p.revision}{p.stale?' · 过期':''}</h3><MarkdownBody>{p.data.hypothesis}</MarkdownBody><MarkdownBody>{p.data.whyUseful}</MarkdownBody><details open><summary>对照、风险与所需证据</summary><pre>{JSON.stringify(p.data,null,2)}</pre></details></article>)}<button onClick={()=>setTab('code')}>查看并编辑实验计划</button></section>}
      {tab==='code'&&<StudyCodeLab sessionId={sessionId} state={state} codeEnabled={codeEnabled} onSaved={settled}/>}
      {tab==='visual'&&<MathVisualizationPanel key={sessionId} sessionId={sessionId}/>}
    </>:<p role="status">读取已保存的学习项目…</p>}
  </main><StudyConversation key={sessionId} sessionId={sessionId} onOpenFile={openFile} onReady={setReady} onSettled={settled}/>{preview&&<WorkspaceFilePreview target={{kind:'file',...preview}} sessionId={sessionId} onClose={closeFile} onOpenFile={path=>openFile(path,state?.project.root)}/>}</div>;
}
function Content(){const params=useSearchParams();const sid=params.get('sessionId');return <I18nProvider>{sid?<Workspace key={sid} sessionId={sid}/>:<Start/>}</I18nProvider>;}
export default function StudyResearchPage(){return <Suspense fallback={<p>加载学习工作区…</p>}><Content/></Suspense>;}
